<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Chalmers.ILL.Tests</RootNamespace>
    <AssemblyName>Chalmers.ILL.Tests</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Web.Abstractions" />
    <Reference Include="System.Web.Routing" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EWS-Api-2.0" Version="1.0.1" />
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="4.0.20710.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.0" />
    <PackageReference Include="Microsoft.AspNet.WebPages" Version="2.0.20710.0" />
    <PackageReference Include="Unity" Version="3.0.1304.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chalmers.ILL\Chalmers.ILL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Mail\Data\reprints-desk-mail.txt" />
    <EmbeddedResource Include="Mail\Data\reprints-desk-mail-links-removed.txt" />
  </ItemGroup>

</Project>
